const Menu = [
  {
    id: 1,
    image: "images/maggi.jpg",
    name: "maggi",
    category: "breakfast",
    price: "Rs 12",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 2,
    image: "images/aloopakoda.jpg",
    name: "aloo pakoda",
    category: "dinner",
    price: "Rs 20",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "breakfast",
    price: "Rs 10",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 4,
    image: "images/chola.jpg",
    name: "chola",
    category: "lunch",
    price: "Rs 52",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 5,
    image: "images/pizza.jpg",
    name: "pizza",
    category: "evening",
    price: "Rs 80",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 6,
    image: "images/non.jpg",
    name: "non-veg thali",
    category: "lunch",
    price: "Rs 180",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 7,
    image: "images/sweets.jpg",
    name: "sweets",
    category: "evening",
    price: "Rs 60",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 8,
    image: "images/rajma.jpg",
    name: "rajma rice",
    category: "dinner",
    price: "Rs 60",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 9,
    image: "images/samosa.jpg",
    name: "samosa",
    category: "evening",
    price: "Rs 10",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
];
export default Menu;
